---
title: "DC Bike Rentals"
output: html_notebook
---


### Loading Packages
```{r}
library(tidyverse)
library(tidymodels)
library(dsbox)
```
...
### Recoding Data
```{r}
# Recode the season variable to be a factor with level names

dcbikeshare <- dcbikeshare %>%
  mutate(
    season = case_when(
    season == 1 ~ "winter",
    season == 2 ~ "spring",
    season == 3 ~ "summer",
    season == 4 ~ "fall"
    ),
    season = fct_relevel(season,"spring","summer","fall","winter")
  )

# Recode holiday and workingday

dcbikeshare <- dcbikeshare %>%
  mutate(
    holiday = ifelse(holiday == 0, "no", "yes"),      
    holiday = fct_relevel(holiday, "no", "yes"),    
    workingday = ifelse(workingday == 0, "no", "yes"),
    workingday = fct_relevel(workingday, "no", "yes")
  )

# Recode Year
dcbikeshare <- dcbikeshare %>%
  mutate(
    yr = ifelse(yr == 0, "2011", "2012"),
    yr = fct_relevel(yr, "2011", "2012")
  )

# Recode weathersit
dcbikeshare <- dcbikeshare %>%
  mutate(
    weathersit = case_when(
      weathersit == 1 ~ "clear",
      weathersit == 2 ~ "mist",
      weathersit == 3 ~ "light precipitation",
      weathersit == 4 ~ "heavy precipitation"
    ),
    weathersit = fct_relevel(weathersit, "clear", "mist", "light precipitation", "heavy precipitation")
  )
```
...

### Creating New Variables

```{r}
dcbikeshare <- dcbikeshare %>%
  mutate(
    temperature_raw = temp * 41,
    feeling_temperature_raw = atemp * 50,
    humidity_raw = hum * 100,
    windspeed_raw = windspeed * 67
  )

dcbikeshare %>%
  mutate(cas_plus_reg = casual + registered) %>%
  summarise(all_zero = all(cas_plus_reg == cnt))


```
...

### Bike Rentals and Temperature

```{r}
dcbikeshare %>%
  ggplot(mapping = aes(x = dteday, y = cnt, color = feeling_temperature_raw)) +
    geom_point(alpha = 0.7) +
    labs(
      title = "Bike rentals in DC, 2011 and 2012",
      subtitle = "Warmer temperatures associated with more bike rentals",
      x = "Date",
      y = "Bike rentals",
      color = "Temperature (C)"
    ) +
  theme_minimal()
```
...
### Linear Regression Model
```{r}
cnt_tmp <- linear_reg() %>%
  set_engine("lm") %>%
  fit(cnt ~ temperature_raw, data = dcbikeshare)
cnt_tmp %>%
  tidy()

glance(cnt_tmp)$r.squared
```
```{r}
# The model predicts for a temperature of 0, we would expect 1215 rentals and for each additional degree warmer, we would expect 162 more rentals.The R-Squared of .3937 tells us 39% of the variation in rentals can be explained by temperature.
```
...
### Linear Regression for real feel
```{r}
cnt_atmp <- linear_reg() %>%
  set_engine("lm") %>%
  fit(cnt ~ feeling_temperature_raw, data = dcbikeshare)
cnt_atmp %>%
  tidy()

glance(cnt_atmp)$r.squared
```
...
### Full Linear Regression Model
```{r}
cnt_full <- linear_reg() %>%
  set_engine("lm") %>%
  fit(cnt ~ season + yr + holiday + workingday + weathersit +
        temperature_raw + feeling_temperature_raw + humidity_raw +
        windspeed_raw + feeling_temperature_raw * holiday, 
      data = dcbikeshare)
tidy(cnt_full)

glance(cnt_full)$adj.r.squared
```


